MedicalApp.WebApp/Models/DiagnosisViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Models
{
    public class DiagnosisViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public int AppointmentId { get; set; }
        [Display(Name = "Comentarios")]
        [MaxLength(1000, ErrorMessage = "No puede ingresar mas de 1000 carácteres")]
        [Required(ErrorMessage = "Ingrese un comentario")]
        public string Comments { get; set; }
        public AppointmentViewModel Appointment { get; set; }
        public List<DiagnosisFileViewModel> Files { get; set; }
        public DiagnosisViewModel()
        {
            Files = new List<DiagnosisFileViewModel>();
        }
    }
}

MedicalApp.WebApp/Controllers/DiagnosisController.cs
using MedicalApp.WebApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{

    public class DiagnosisController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        private IHostingEnvironment _env;
        public DiagnosisController(IConfiguration configuration, IHostingEnvironment env)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
            _env = env;
        }
        public async Task<IActionResult> Index(int appointmentId)
        {
            DiagnosisViewModel model = new DiagnosisViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Diagnosis/" + appointmentId))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<DiagnosisViewModel>(apiResponse);
                    }
                }
            }
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(DiagnosisViewModel model, IList<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                int diagnosisId = 0;
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(_apiBaseUrl + "/api/Diagnosis", contentData))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            diagnosisId = Convert.ToInt32(apiResponse);
                        }
                    }
                }

                try
                {
                    if(diagnosisId != 0)
                    {
                        foreach (var f in files)
                        {
                            if (f.Length > 0)
                            {
                                DiagnosisFileViewModel file = new DiagnosisFileViewModel();
                                file.DiagnosisId = diagnosisId;
                                file.Name = Path.GetFileName(f.FileName);
                                file.Type = Path.GetExtension(f.FileName);
                                int diagnosisFileId = 0;
                                using (var httpClient = new HttpClient())
                                {
                                    string stringData = JsonConvert.SerializeObject(file);
                                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                                    using (var response = await httpClient.PostAsync(_apiBaseUrl + "/api/DiagnosisFile", contentData))
                                    {
                                        if (response.StatusCode == HttpStatusCode.OK)
                                        {
                                            string apiResponse = await response.Content.ReadAsStringAsync();
                                            var modelResponse = JsonConvert.DeserializeObject<DiagnosisFileViewModel>(apiResponse);
                                            diagnosisFileId = modelResponse.Id;
                                        }
                                    }
                                }

                                if(diagnosisFileId != 0)
                                {
                                    var rootPath = Path.Combine(_env.WebRootPath, "Files");
                                    if (!Directory.Exists(rootPath))
                                        Directory.CreateDirectory(rootPath);
                                    var name = diagnosisFileId.ToString() + file.Type;
                                    var filePath = Path.Combine(rootPath, name);
                                    using (FileStream fs = System.IO.File.Create(filePath))
                                    {
                                        f.CopyTo(fs);
                                    }
                                }
                            }
                        }
                    }
                }
                catch(Exception ex)
                {

                }


                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Diagnosis/" + model.AppointmentId))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            model = JsonConvert.DeserializeObject<DiagnosisViewModel>(apiResponse);
                        }
                    }
                }

                
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", model) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Index", model) });
        }

        public async Task<FileResult> DownloadFile(int id) {

            DiagnosisFileViewModel model = new DiagnosisFileViewModel();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/DiagnosisFile/" + id))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<DiagnosisFileViewModel>(apiResponse);
                    }
                }
            }

            string path = Path.Combine(_env.WebRootPath, "Files/") + model.Id.ToString() + model.Type;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", model.Name);
        }
    }
}

MedicalApp.WebApp/Views/Diagnosis/Index.cshtml
@model MedicalApp.WebApp.Models.DiagnosisViewModel

@{
    ViewData["Title"] = "Agregar diagnostico";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="Index" onsubmit="return AddOrEditDiagnosis(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.AppointmentId)
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            @if (Model.Files.Count > 0)
            {
                <h5 class="mt-2 text-muted">Archivos de Diagnóstico</h5>
                <ul class="list-unstyled">
                    @foreach (var item in Model.Files)
                    {
                        <li>
                            <a href="@Url.Action("DownloadFile", "Diagnosis", new { id = item.Id })" target="_blank" class="btn-link text-secondary">
                                <i class="far fa-fw fa-file-pdf"></i>
                                @item.Name
                            </a>
                        </li>
                    }
                </ul>
            }
            <div class="card bg-gray-light">
                <div class="card-body m-0">
                    <input type="file" name="files" accept=".jpg,.jpeg,.png,.pdf" multiple/>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-12">
                    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
                    <input type="submit" value="Agregar diagnostico" class="btn btn-info float-right">
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}