MedicalApp.WebApp/Controllers/ClinicController.cs
using MedicalApp.WebApp.Attributes;
using MedicalApp.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{
    [TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class ClinicController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        public ClinicController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
        }
        // GET: ClinicController
        public async Task<ActionResult> Index()
        {
            List<ClinicViewModel> clinics = new List<ClinicViewModel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                    }
                }
            }
            return View(clinics);
        }

        // GET: ClinicController/Create
        public ActionResult Create()
        {
            ClinicViewModel model = new ClinicViewModel
            {
                IsActive = true
            };
            return View(model);
        }

        // POST: ClinicController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Name,Address,WebSite,Email,Telephone,IsActive")] ClinicViewModel model)
        {
            if (ModelState.IsValid)
            {
                ClinicViewModel clinic = new ClinicViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(_apiBaseUrl + "/api/Clinic", contentData))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinic = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                        }
                    };
                }

                List<ClinicViewModel> clinics = new List<ClinicViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                        }
                    }
                }

                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", clinics) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }

        // GET: ClinicController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ClinicViewModel model = new ClinicViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic/" + id))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }

        // POST: ClinicController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,Name,Address,WebSite,Email,Telephone,IsActive")] ClinicViewModel model)
        {
            if (ModelState.IsValid)
            {
                ClinicViewModel clinic = new ClinicViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8,"application/json");
                    using (var response = await httpClient.PutAsync(_apiBaseUrl + "/api/Clinic/" + id, contentData)) {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinic = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                        }
                    };
                }

                List<ClinicViewModel> clinics = new List<ClinicViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                        }
                    }
                }

                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", clinics) });
                    
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            ClinicViewModel model = new ClinicViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic/" + id))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }
    }
}

MedicalApp.WebApp/Controllers/SearchController.cs
using MedicalApp.WebApp.Attributes;
using MedicalApp.WebApp.Models;
using MedicalApp.WebApp.Models.Auth;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{
    [TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class SearchController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        public SearchController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
        }
        public async Task<IActionResult> Index(SearchAppointmentViewModel model)
        {

            if (model.DateStart == null || model.DateEnd == null)
            {
                //var today = DateTime.Now;
                //var firstDayOfMonth = new DateTime(today.Year, today.Month, 1);
                //var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);
                //model.DateStart = firstDayOfMonth;
                //model.DateEnd = lastDayOfMonth;
                model.DateStart = DateTime.Now;
                model.DateEnd = DateTime.Now;
                ModelState.Clear();
            }

            model.ListOfClinics = GetClinics();
            model.ListOfDoctors = GetDoctors();
            model.ListOfPatients = GetPatients();

            model.Appointments = new List<AppointmentViewModel>();
            using (var httpClient = new HttpClient())
            {
                string parameters = string.Empty;
                if (model.ClincId != null)
                    parameters = parameters + "clinicId=" + model.ClincId.ToString() + "&";
                if (model.DoctorId != null)
                {
                    parameters = parameters + "doctorId=" + model.DoctorId.ToString() + "&";
                }
                else
                {
                    parameters = parameters + "doctorId=" + model.ListOfDoctors.FirstOrDefault().Value + "&";
                }

                if (model.Status != null)
                    parameters = parameters + "status=" + (int)model.Status + "&";

                if (model.PatientId != null)
                    parameters = parameters + "patientId=" + model.PatientId.ToString() + "&";

                var dateStart = (DateTime)model.DateStart;
                var dateEnd = (DateTime)model.DateEnd;
                parameters = parameters + "dateTimeStart=" + dateStart.ToString("yyyy-MM-dd 00:00") + "&";
                parameters = parameters + "dateTimeEnd=" + dateEnd.ToString("yyyy-MM-dd 23:59");

                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Appointment?" + parameters))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model.Appointments = JsonConvert.DeserializeObject<List<AppointmentViewModel>>(apiResponse);
                    }
                }
            }
            return View(model);
        }

        public List<SelectListItem> GetClinics()
        {
            var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Clinic");
            var data = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);

            List<SelectListItem> list = data
                .OrderBy(n => n.Name)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name
                }).ToList();
            var selectOption = new SelectListItem()
            {
                Value = "",
                Text = "--- Seleccionar Clínica ---"
            };

            list.Insert(0, selectOption);
            return list;
        }

        //public List<SelectListItem> GetDoctors()
        //{
        //    var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor");
        //    var data = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);

        //    List<SelectListItem> list = data
        //        .OrderBy(n => n.Name)
        //        .Select(n => new SelectListItem
        //        {
        //            Value = n.Id.ToString(),
        //            Text = n.Name + " " + n.LastName
        //        }).ToList();
        //    var selectOption = new SelectListItem()
        //    {
        //        Value = "",
        //        Text = "--- Seleccionar Doctor ---"
        //    };

        //    list.Insert(0, selectOption);
        //    return list;
        //}
        public List<SelectListItem> GetDoctors()
        {
            var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor");
            var data = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);
            var login = JsonConvert.DeserializeObject<LoginResponseViewModel>(HttpContext.Session.GetString(SessionKeys.Login));
            List<SelectListItem> list = new List<SelectListItem>();


            if (login.IsInRole("Administrator"))
            {
                list = data
                .OrderBy(n => n.Name)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name + " " + n.LastName
                }).ToList();

                var selectOption = new SelectListItem()
                {
                    Value = "",
                    Text = "--- Seleccionar Doctor ---"
                };

                list.Insert(0, selectOption);
            }
            else
            {
                var apiResponseDoctor = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor/GetByUserId/" + login.UserId);
                var doctor = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponseDoctor);
                var optionDoctor = data.Where(d => d.Id == doctor.Id).FirstOrDefault();
                list.Insert(0, new SelectListItem { Value = optionDoctor.Id.ToString(), Text = optionDoctor.Name + " " + optionDoctor.LastName });
            }
            return list;
        }

        public List<SelectListItem> GetPatients()
        {
            var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Patient");
            var data = JsonConvert.DeserializeObject<List<PatientViewModel>>(apiResponse);

            List<SelectListItem> list = data
                .OrderBy(n => n.Name)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name + " " + n.LastName
                }).ToList();
            var selectOption = new SelectListItem()
            {
                Value = "",
                Text = "--- Seleccionar Paciente ---"
            };

            list.Insert(0, selectOption);
            return list;
        }
    }
}

MedicalApp.WebApp/Views/Search/Index.cshtml
@model MedicalApp.WebApp.Models.SearchAppointmentViewModel

@{
    ViewData["Title"] = "Busqueda de Citas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Búsqueda de Citas</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">

            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Filtros</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        @using (Html.BeginForm("Index", "Search", FormMethod.Get))
                        {
                            <div class="row">
                                <div class="form-group col-md-3">
                                    <label asp-for="ClincId" class="control-label"></label>
                                    <select asp-for="ClincId" asp-items="Model.ListOfClinics" class="form-control"></select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label asp-for="DoctorId" class="control-label">Doctor</label>
                                    <select asp-for="DoctorId" asp-items="Model.ListOfDoctors" class="form-control"></select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label asp-for="PatientId" class="control-label"></label>
                                    <select asp-for="PatientId" asp-items="Model.ListOfPatients" class="form-control"></select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Status" class="control-label"></label>
                                    <select asp-for="Status" asp-items="Html.GetEnumSelectList<AppointmentStatus>()" class="form-control">
                                        <option selected="selected" value="">Seleccionar</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-2">
                                    <label class="control-label">Fecha Inicio</label>
                                    <input asp-for="DateStart" type="date" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="DateStart" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-2">
                                    <label class="control-label">Fecha Fin</label>
                                    <input asp-for="DateEnd" type="date" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="DateEnd" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary btn-block">Buscar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="view-all">
                    @await Html.PartialAsync("_ViewAll", Model)
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->

@section Scripts{

    <script type="text/javascript">
        AddOrEditDiagnosis = form => {
            try {
                $.ajax({
                    type: 'POST',
                    url: form.action,
                    data: new FormData(form),
                    contentType: false,
                    processData: false,
                    success: function (res) {
                        if (res.isValid) {
                            console.log(JSON.stringify(res))
                            $('#form-modal').modal('hide')
                            
                            location.reload()
                        }
                        else {
                            $('#form-modal .modal-body').html(res.html);
                        }
                    },
                    error: function (err) {
                        console.log(err)
                    }
                })
                //to prevent default form submit event
                return false;
            } catch (ex) {
                console.log(ex)
            }
        }
    </script>
}

MedicalApp.WebApp/Views/Search/_ViewAll.cshtml
@model  MedicalApp.WebApp.Models.SearchAppointmentViewModel

<table class="table table-hover">
    <thead class="bg-primary text-white">
        <tr>
            <th>
                ID
            </th>
            <th>
                Razón
            </th>
            <th>
                Fecha/Hora Inicio
            </th>
            <th>
                Fecha/Hora Fin
            </th>
            <th>
                Clínica
            </th>
            <th>
                Doctor
            </th>
            <th>
                Paciente
            </th>
            <th>
                Estado
            </th>
            <th>
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Appointments)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reason)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTimeEnd)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("Details","Clinic",new {id=item.ClinicId}, "https")','Clínica')" href="#">@Html.DisplayFor(modelItem => item.Clinic.Name)</a>
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("Details","Doctor",new {id=item.DoctorId}, "https")','Doctor')" href="#">@string.Format("{0} {1}", item.Doctor.Name, item.Doctor.LastName)</a>
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("Details","Patient",new {id=item.PatientId}, "https")','Paciente')" href="#">@string.Format("{0} {1}", item.Patient.Name, item.Patient.LastName)</a>
            </td>
            <td>
                @if (item.Status == AppointmentStatus.Programada)
                {
                    <span class="badge badge-warning">@item.Status</span>
                }
                else if (item.Status == AppointmentStatus.Confirmada)
                {
                    <span class="badge badge-primary">@item.Status</span>
                }
                else if (item.Status == AppointmentStatus.Finalizada)
                {
                    <span class="badge badge-success">@item.Status</span>
                }
                else if (item.Status == AppointmentStatus.Cancelada)
                {
                    <span class="badge badge-secondary">@item.Status</span>
                }
            </td>
            <td>
                <a href="#" alt="Ver detalle" class="btn btn-sm btn-primary fa fa-eye" onclick="showInPopup('@Url.Action("Details","Appointment", new { id = item.Id })', 'Detalles de la cita');"></a> <a class="btn btn-sm btn-warning fa fa-edit" alt="Diagnostico" onclick="showInPopup('@Url.Action("Index","Diagnosis",new {appointmentId = item.Id}, "https")','Diagnóstico')"></a>
            </td>
        </tr>
        }
    </tbody>
</table>