MedicalApp.WebApp/Models/AppointmentViewModel.cs
using MedicalApp.WebApp.Attributes;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MedicalApp.WebApp.Models
{
    public class AppointmentViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Clínica")]
        public int? ClinicId { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Doctor")]
        public int? DoctorId { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Paciente")]
        public int? PatientId { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Fecha/Hora Inicio")]
        [DateGreaterThan("DateTimeEnd")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [DataType(DataType.DateTime)]
        public DateTime? DateTimeStart { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Fecha/Hora Fin")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [DataType(DataType.DateTime)]
        public DateTime? DateTimeEnd { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Razón")]
        public string Reason { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Nota")]

        public string Note { get; set; }
        public int? UserId { get; set; }
        [Display(Name = "Estado")]
        public AppointmentStatus Status { get; set; }
        public ClinicViewModel Clinic { get; set; }
        public DoctorViewModel Doctor { get; set; }
        public PatientViewModel Patient { get; set; }

        public List<SelectListItem> ListOfClincs { get; set; }
        public List<SelectListItem> ListOfDoctors { get; set; }
        public List<SelectListItem> ListOfPatients { get; set; }
    }

    public enum AppointmentStatus
    {
        Programada = 1,
        Confirmada = 2,
        Finalizada = 3,
        Cancelada = 4
    }
}

MedicalApp.WebApp/Controllers/AppointmentController.cs
using MedicalApp.WebApp.Attributes;
using MedicalApp.WebApp.Models;
using MedicalApp.WebApp.Models.Auth;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{
    [TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class AppointmentController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        public AppointmentController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
        }
        public IActionResult Index()
        {
            ViewBag.Clinics = GetClinics();
            ViewBag.Doctors = GetDoctors();
            ViewBag.Patients = GetPatients();

            bool showAddAppointmentButton = true;
            var login = JsonConvert.DeserializeObject<LoginResponseViewModel>(HttpContext.Session.GetString(SessionKeys.Login));
            if (login.IsInRole("Doctor"))
            {
                var apiResponseDoctor = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor/GetByUserId/" + login.UserId);
                var doctor = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponseDoctor);
                if (!doctor.IsAvailable)
                    showAddAppointmentButton = false;
            }
            ViewBag.ShowAddAppointmentButton = showAddAppointmentButton;

            return View();
        }
        public ActionResult Create()
        {
            AppointmentViewModel model = new AppointmentViewModel();
            model.ListOfClincs = GetClinics();
            model.ListOfDoctors = GetAvailableDoctors("Create");
            model.ListOfPatients = GetPatients();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("ClinicId,DoctorId,PatientId,DateTimeStart,DateTimeEnd,Reason,Note")] AppointmentViewModel model)
        {
            model.ListOfClincs = GetClinics();
            model.ListOfDoctors = GetAvailableDoctors();
            model.ListOfPatients = GetPatients();
            if (ModelState.IsValid)
            {
                AppointmentViewModel appointment = new AppointmentViewModel();
                var login = JsonConvert.DeserializeObject<LoginResponseViewModel>(HttpContext.Session.GetString(SessionKeys.Login));
                model.UserId = login.UserId;
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(_apiBaseUrl + "/api/Appointment", contentData))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            appointment = JsonConvert.DeserializeObject<AppointmentViewModel>(apiResponse);
                        }
                        else if (response.StatusCode == HttpStatusCode.BadRequest)
                        {
                            ModelState.AddModelError(nameof(AppointmentViewModel.DateTimeStart), await response.Content.ReadAsStringAsync());
                            ModelState.AddModelError(nameof(AppointmentViewModel.DateTimeEnd), await response.Content.ReadAsStringAsync());
                            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
                        }
                    };
                }

                return Json(new { isValid = true, html = "" });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }
        public async Task<IActionResult> Edit(int id)
        {
            AppointmentViewModel model = new AppointmentViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Appointment/" + id))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<AppointmentViewModel>(apiResponse);
                    }
                }
            }

            model.ListOfClincs = GetClinics();
            model.ListOfDoctors = GetAvailableDoctors();
            model.ListOfPatients = GetPatients();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,ClinicId,DoctorId,PatientId,DateTimeStart,DateTimeEnd,Reason,Note,Status")] AppointmentViewModel model)
        {
            model.ListOfClincs = GetClinics();
            model.ListOfDoctors = GetAvailableDoctors();
            model.ListOfPatients = GetPatients();
            if (ModelState.IsValid)
            {
                AppointmentViewModel appointment = new AppointmentViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync(_apiBaseUrl + "/api/Appointment/" + id, contentData))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            appointment = JsonConvert.DeserializeObject<AppointmentViewModel>(apiResponse);
                        }
                        else if (response.StatusCode == HttpStatusCode.BadRequest)
                        {
                            ModelState.AddModelError(nameof(AppointmentViewModel.DateTimeStart), await response.Content.ReadAsStringAsync());
                            ModelState.AddModelError(nameof(AppointmentViewModel.DateTimeEnd), await response.Content.ReadAsStringAsync());
                            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
                        }
                    };
                }

                return Json(new { isValid = true, html = "" });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }
        public async Task<ActionResult> Details(int id)
        {
            AppointmentViewModel model = new AppointmentViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Appointment/" + id + "/GetDetails"))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<AppointmentViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }
        public List<SelectListItem> GetClinics()
        {
            var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Clinic");
            var data = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);

            List<SelectListItem> list = data
                .OrderBy(n => n.Name)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name
                }).ToList();
            var selectOption = new SelectListItem()
            {
                Value = "",
                Text = "--- Seleccionar Clínica ---"
            };

            list.Insert(0, selectOption);
            return list;
        }
        public List<SelectListItem> GetDoctors()
        {
            var apiResponse = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor");
            var data = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);
            var login = JsonConvert.DeserializeObject<LoginResponseViewModel>(HttpContext.Session.GetString(SessionKeys.Login));
            List<SelectListItem> list = new List<SelectListItem>();


            if (login.IsInRole("Administrator"))
            {
                list = data
                .OrderBy(n => n.Name)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name + " " + n.LastName
                }).ToList();

                var selectOption = new SelectListItem()
                {
                    Value = "",
                    Text = "--- Seleccionar Doctor ---"
                };

                list.Insert(0, selectOption);
            }
            else
            {
                var apiResponseDoctor = new WebClient().DownloadString(_apiBaseUrl + "/api/Doctor/GetByUserId/" + login.UserId);
                var doctor = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponseDoctor);
                var optionDoctor = data.Where(d => d.Id == doctor.Id).FirstOrDefault();

MedicalApp.WebApp/Views/Appointment/Create.cshtml
@model MedicalApp.WebApp.Models.AppointmentViewModel

@{
    ViewData["Title"] = "Agregar nueva cita";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" onsubmit="return AddOrEditAppointment(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClinicId" class="control-label"></label>
                <select asp-for="ClinicId" asp-items="Model.ListOfClincs" class="form-control"></select>
                <span asp-validation-for="ClinicId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" asp-items="Model.ListOfDoctors" class="form-control"></select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select asp-for="PatientId" asp-items="Model.ListOfPatients" class="form-control"></select>
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="DateTimeStart" class="control-label"></label>
                        <input asp-for="DateTimeStart" placeholder="DD/MM/YYYY HH:mm" class="form-control"/>
                        @*<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                            <input asp-for="DateTimeStart" type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" autocomplete="off" />
                            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>*@
                        <span asp-validation-for="DateTimeStart" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="DateTimeEnd" class="control-label"></label>
                        <input asp-for="DateTimeEnd" placeholder="DD/MM/YYYY HH:mm" class="form-control" />
                        @*<div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                            <input asp-for="DateTimeEnd" type="text" class="form-control datetimepicker-input" data-target="#datetimepicker2" autocomplete="off" />
                            <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>*@
                        <span asp-validation-for="DateTimeEnd" class="text-danger"></span>
                    </div>              
                </div>    
                @*<script type="text/javascript">
                    $(function () {
                        $('#datetimepicker1').datetimepicker({
                            format: 'DD/MM/YYYY HH:mm',
                            useCurrent: false,
                            showTodayButton: true,
                            showClear: true,
                            toolbarPlacement: 'bottom',
                            sideBySide: true,
                            stepping: 15,
                            icons: {
                                time: "fa fa-clock-o",
                                date: "fa fa-calendar",
                                up: "fa fa-arrow-up",
                                down: "fa fa-arrow-down",
                                previous: "fa fa-chevron-left",
                                next: "fa fa-chevron-right",
                                today: "fa fa-clock-o",
                                clear: "fa fa-trash-o"
                            }
                        });

                        $('#datetimepicker2').datetimepicker({
                            format: 'DD/MM/YYYY HH:mm',
                            useCurrent: false,
                            showTodayButton: true,
                            showClear: true,
                            toolbarPlacement: 'bottom',
                            sideBySide: true,
                            stepping: 15,
                            icons: {
                                time: "fa fa-clock-o",
                                date: "fa fa-calendar",
                                up: "fa fa-arrow-up",
                                down: "fa fa-arrow-down",
                                previous: "fa fa-chevron-left",
                                next: "fa fa-chevron-right",
                                today: "fa fa-clock-o",
                                clear: "fa fa-trash-o"
                            }
                        });
                    });
                </script>*@
            </div>
            <div class="form-group">
                <label asp-for="Reason" class="control-label"></label>
                <input asp-for="Reason" class="form-control" autocomplete="off" />
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <textarea asp-for="Note" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <hr />
            <div class="row">
                <div class="col-12">
                    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
                    <input type="submit" value="Agregar nueva cita" class="btn btn-info float-right">
                </div>
            </div>
        </form>
    </div>
</div>

MedicalApp.WebApp/Views/Appointment/Details.cshtml
@model MedicalApp.WebApp.Models.AppointmentViewModel
@{
    ViewData["Title"] = "Detalles de la cita";
    Layout = null;
}
<div>
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.ClinicId)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Clinic.Name)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Doctor.FullName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Patient.FullName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.DateTimeStart)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.DateTimeStart)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.DateTimeEnd)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.DateTimeEnd)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-8">
            @if (Model.Status == AppointmentStatus.Programada)
            {
                <span class="badge badge-warning">@Model.Status</span>
            }
            else if (Model.Status == AppointmentStatus.Confirmada)
            {
                <span class="badge badge-primary">@Model.Status</span>
            }
            else if (Model.Status == AppointmentStatus.Finalizada)
            {
                <span class="badge badge-success">@Model.Status</span>
            }
            else if (Model.Status == AppointmentStatus.Cancelada)
            {
                <span class="badge badge-secondary">@Model.Status</span>
            }
        </dd>
    </dl>
</div>
<div class="row">
    <div class="col-12">
        <a href="#" class="btn btn-secondary" data-dismiss="modal">Cerrar</a>
        @*<a href="#" class="btn btn-info float-right" onclick="showInPopup('@Url.Action("Edit","Appointment", new { id = Model.Id })', 'Editar cita');">Editar</a>*@
    </div>
</div>

MedicalApp.WebApp/Views/Appointment/Index.cshtml
@{
    ViewData["Title"] = "Citas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/lib/fullcalendar/css/main.css" />
<script type="text/javascript" src="~/lib/fullcalendar/js/main.js"></script>
<script type="text/javascript" src="~/lib/fullcalendar/js/locales-all.js"></script>

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Citas</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                @if (ViewBag.ShowAddAppointmentButton)
                {
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <a onclick="showInPopup('@Url.Action("Create","Appointment")','Agregar nueva cita')" class="btn btn-success btn-block">Agregar nueva cita</a>
                        </div>
                    </div>
                }
                <div class="row">
                    <div class="col-md-12">
                        <div class="sticky-top mb-3">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Búsqueda</h4>
                                </div>
                                <div class="card-body">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="ddlClinic">Clínica</label>
                                            @Html.DropDownList("ddlClinic", (IEnumerable<SelectListItem>)ViewBag.Clinics, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            <label for="ddlDoctor">Doctor</label>
                                            @Html.DropDownList("ddlDoctor", (IEnumerable<SelectListItem>)ViewBag.Doctors, new { @class = "form-control" })
                                        </div>
                                        <div class="form-group">
                                            <label for="ddlPatient">Paciente</label>
                                            @Html.DropDownList("ddlPatient", (IEnumerable<SelectListItem>)ViewBag.Patients, new { @class = "form-control" })
                                        </div>
                                        <a class="btn btn-primary btn-block" onclick="GetAppointments();">Buscar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-9">
                <div class="card card-primary">
                    <div class="card-body p-0">
                        <div id="calendar"></div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</div>
<!-- /.content -->

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script type="text/javascript">
    GetAppointments = function () {
        var clinicId = $("#ddlClinic").val();
        var doctorId = $("#ddlDoctor").val();
        var patientId = $("#ddlPatient").val();

        FecthAndRenderCalendar(clinicId, doctorId, patientId);
    };

    FecthAndRenderCalendar = function (clinicId, doctorId, patientId) {
        //alert("Clinc: " + clinicId + " - Doctor: " + doctorId + " - Patient: " + patientId);
        //alert("@Url.Action("GetAppointments", "Appointment")/" + clinicId + "/" + doctorId + "/" + patientId)
        appointments = [];

        $.ajax({
            type: "GET",
            url: "@Url.Action("GetAppointments", "Appointment")",
            data: {
                clinicId: clinicId,
                doctorId: doctorId,
                patientId: patientId
            },
            success: function (data) {
                console.log("Data: " + JSON.stringify(data));
                $.each(data, function (i, v) {
                    console.log("eventID: " + v.id);

                    appointments.push({
                        eventID: v.id,
                        title: v.reason,
                        description: v.note,
                        start: v.dateTimeStart,
                        end: v.dateTimeEnd,
                        color: (v.status == 1) ? "#ffc107" : (v.status == 2) ? "#007bff" : (v.status == 3) ? "#28a745" : (v.status == 4) ? "#6c757d" : "",
                        textColor: (v.status == 1) ? "#000000" : (v.status == 2) ? "#ffffff" : (v.status == 3) ? "#ffffff" : (v.status == 4) ? "#ffffff" : "#ffffff",
                        allDay: false
                    });
                });

                GenerateCalendar(appointments);
            },
            error: function (error) {
                alert('Ha ocurrido un error al crear el calendario de citas...');
            }
        });
    };

    GenerateCalendar = function (appointments) {
        var initialLocaleCode = 'es';
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            themeSystem: 'bootstrap',
            locale: initialLocaleCode,
            initialView: 'timeGridWeek',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
            },
            selectable: true,
            events: appointments,
            eventClick: function (calEvent) {
                console.log('eventId: ' + calEvent.event.extendedProps.eventID);
                showInPopup('@Url.Action("Edit","Appointment")/' + calEvent.event.extendedProps.eventID, 'Editar cita');
                @*showInPopup('@Url.Action("Details","Appointment")/' + calEvent.event.extendedProps.eventID, 'Detalles de la cita');*@
            },
            //select: function (start, end) {
            //    selectedEvent = {
            //        eventID: 0,
            //        title: '',
            //        description: '',
            //        start: start,
            //        end: end,
            //        allDay: false,
            //        color: ''
            //    };

            //},
            editable: false
        });
        calendar.render();
    };

        $(document).ready(function () {
            var appointments = [];
            var selectedAppointment = null;
            //FecthAndRenderCalendar(0, 0, 0);

            //GenerateCalendar();
            GetAppointments();

            AddOrEditAppointment = form => {
                try {
                    $.ajax({
                        type: 'POST',
                        url: form.action,
                        data: new FormData(form),
                        contentType: false,
                        processData: false,
                        success: function (res) {
                            if (res.isValid) {
                                //FecthAndRenderCalendar();
                                GetAppointments();
                                $('#form-modal .modal-body').html('');
                                $('#form-modal .modal-title').html('');
                                $('#form-modal').modal('hide');
                            }
                            else
                                $('#form-modal .modal-body').html(res.html);
                        },
                        error: function (err) {
                            console.log(err)
                        }
                    })
                    //to prevent default form submit event
                    return false;
                } catch (ex) {
                    console.log(ex)
                }
            }
        });

        //$(function () {
        //    $('#dtpDateTimeStart').datetimepicker();
        //});
        //$(function () {
        //    $('#dtpDateTimeEnd').datetimepicker();
        //});
</script>
}

<style>
    #calendar.fc-theme-bootstrap {
        font-size: 14px;
    }

    #top {
        background: #eee;
        border-bottom: 1px solid #ddd;
        padding: 0 10px;
        line-height: 40px;
        font-size: 12px;
        color: #000;
    }

        #top .selector {
            display: inline-block;
            margin-right: 10px;
        }

        #top select {
            font: inherit; /* mock what Boostrap does, don't compete  */
        }

    #calendar {
        max-width: 1100px;
        margin: 40px auto;
        padding: 0 10px;
    }
</style>