MedicalApp.WebApp/Controllers/ClinicController.cs
using MedicalApp.WebApp.Attributes;
using MedicalApp.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{
    [TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class ClinicController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        public ClinicController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
        }
        // GET: ClinicController
        public async Task<ActionResult> Index()
        {
            List<ClinicViewModel> clinics = new List<ClinicViewModel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                    }
                }
            }
            return View(clinics);
        }

        // GET: ClinicController/Create
        public ActionResult Create()
        {
            ClinicViewModel model = new ClinicViewModel
            {
                IsActive = true
            };
            return View(model);
        }

        // POST: ClinicController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Name,Address,WebSite,Email,Telephone,IsActive")] ClinicViewModel model)
        {
            if (ModelState.IsValid)
            {
                ClinicViewModel clinic = new ClinicViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(_apiBaseUrl + "/api/Clinic", contentData))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinic = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                        }
                    };
                }

                List<ClinicViewModel> clinics = new List<ClinicViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                        }
                    }
                }

                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", clinics) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }

        // GET: ClinicController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ClinicViewModel model = new ClinicViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic/" + id))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }

        // POST: ClinicController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,Name,Address,WebSite,Email,Telephone,IsActive")] ClinicViewModel model)
        {
            if (ModelState.IsValid)
            {
                ClinicViewModel clinic = new ClinicViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8,"application/json");
                    using (var response = await httpClient.PutAsync(_apiBaseUrl + "/api/Clinic/" + id, contentData)) {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinic = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                        }
                    };
                }

                List<ClinicViewModel> clinics = new List<ClinicViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            clinics = JsonConvert.DeserializeObject<List<ClinicViewModel>>(apiResponse);
                        }
                    }
                }

                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", clinics) });
                    
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            ClinicViewModel model = new ClinicViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Clinic/" + id))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<ClinicViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }
    }
}

MedicalApp.WebApp/Controllers/DoctorController.cs
using MedicalApp.WebApp.Attributes;
using MedicalApp.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace MedicalApp.WebApp.Controllers
{
    [TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class DoctorController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _apiBaseUrl;
        public DoctorController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiBaseUrl = _configuration.GetValue<string>("WebAPIBaseUrl");
        }
        public async Task<ActionResult> Index()
        {
            List<DoctorViewModel> doctors = new List<DoctorViewModel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Doctor"))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        doctors = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);
                    }
               }
            }
            return View(doctors);
        }

        // GET: DoctorController/Create
        public ActionResult Create()
        {
            DoctorViewModel model = new DoctorViewModel
            {
                IsAvailable = true
            };
            return View(model);
        }

        // POST: DoctorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name,LastName,BirthDate,Gender,Phone,Speciality,Summary,IsAvailable")] DoctorViewModel model)
        {
            if (ModelState.IsValid)
            {
                DoctorViewModel doctor = new DoctorViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("https://localhost:5001/api/Doctor", contentData))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            doctor = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponse);
                        }
                        else
                        {
                            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
                        }
                    };
                }
                List<DoctorViewModel> doctors = new List<DoctorViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync("https://localhost:5001/api/Doctor"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            doctors = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", doctors) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", model) });
        }

        // GET: DoctorController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            DoctorViewModel model = new DoctorViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Doctor/" + id))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponse);
                    }
                }

            }
            return View(model);
        }

        // POST: DoctorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id, Name,LastName,BirthDate,Gender,Phone,Speciality,Summary,IsAvailable")] DoctorViewModel model)
        {
            if (ModelState.IsValid)
            {
                DoctorViewModel doctor = new DoctorViewModel();
                using (var httpClient = new HttpClient())
                {
                    string stringData = JsonConvert.SerializeObject(model);
                    var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync(_apiBaseUrl + "/api/Doctor/" + id, contentData))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            doctor = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponse);
                        }
                        else
                        {
                            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
                        }
                    };
                }

                List<DoctorViewModel> doctors = new List<DoctorViewModel>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Doctor"))
                    {
                        if(response.StatusCode == HttpStatusCode.OK)
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            doctors = JsonConvert.DeserializeObject<List<DoctorViewModel>>(apiResponse);
                        }
                    }
                }

                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", doctors) });

            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            DoctorViewModel model = new DoctorViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Doctor/" + id))
                {
                    if(response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponse);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Profile(int id)
        {
            DoctorViewModel model = new DoctorViewModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_apiBaseUrl + "/api/Doctor/GetByUserId/" + id))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<DoctorViewModel>(apiResponse);
                    }
                }

            }
            return View("Edit", model);
        }
    }
}

MedicalApp.WebApp/Views/Shared/_AdminHome.cshtml
@model MedicalApp.WebApp.Models.HomeViewModel
<div class="text-center">
    <h1 class="display-4">Agenda del día</h1>
</div>
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>@Model.ScheduledAppointmentsCount</h3>

                <p>Programadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-calendar"></i>
                </div>*@
            @*<a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-primary">
            <div class="inner">
                <h3>@Model.ConfirmedAppointmentsCount</h3>

                <p>Confirmadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-user-injured"></i>
                </div>*@
            @*<a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@Model.FinishedAppointmentsCount</h3>

                <p>Finalizadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-user-md"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-secondary">
            <div class="inner">
                <h3>@Model.CancelledAppointmentsCount</h3>

                <p>Canceladas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-clinic-medical"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            @*<div class="card-header">
                <h3 class="card-title">Citas del día</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>*@
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table m-0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Clínica</th>
                                <th>Doctor</th>
                                <th>Paciente</th>
                                <th>Horario</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Appointments)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Clinic.Name</td>
                                    <td>@string.Format("{0} {1}", item.Doctor.Name, item.Doctor.LastName)</td>
                                    <td>@string.Format("{0} {1}", item.Patient.Name, item.Patient.LastName)</td>
                                    <td>@item.DateTimeStart</td>
                                    <td>
                                        @if (item.Status == AppointmentStatus.Programada)
                                        {
                                            <span class="badge badge-warning">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Confirmada)
                                        {
                                            <span class="badge badge-primary">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Finalizada)
                                        {
                                            <span class="badge badge-success">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Cancelada)
                                        {
                                            <span class="badge badge-secondary">@item.Status</span>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

MedicalApp.WebApp/Views/Shared/_AdminNav.cshtml
@{
    var actionController = ViewContext.RouteData.Values["Controller"].ToString() + "|" + ViewContext.RouteData.Values["Action"].ToString();
}
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Index" class="nav-link @(actionController == "Home|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-home"></i>
            <p>
                Inicio
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Dashboard" asp-action="Index" class="nav-link @(actionController == "Dashboard|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
                Dashboard
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Appointment" asp-action="Index" class="nav-link @(actionController == "Appointment|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-calendar"></i>
            <p>
                Citas
            </p>
        </a>
    </li>
    <li class="nav-item @(actionController == "Search|Index" ? "menu-open" : "" )">
        <a href="#" class="nav-link @(actionController == "Search|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-search"></i>
            <p>
                Consultas
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-controller="Search" asp-action="Index" class="nav-link @(actionController == "Search|Index" ? "active" : "" )">
                    <i class="far fa-calendar nav-icon"></i>
                    <p>Citas</p>
                </a>
            </li>
        </ul>
    </li>
    <li class="nav-item @((actionController == "Clinic|Index" || actionController == "Doctor|Index" || actionController =="Patient|Index" ) ? "menu-open" : "" )">
        <a href="#" class="nav-link @((actionController == "Clinic|Index" || actionController =="Doctor|Index" || actionController == "Patient|Index" ) ? "active" : "" )">
            <i class="nav-icon fas fa-user-cog"></i>
            <p>
                Administración
                <i class="fas fa-angle-left right"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-controller="Clinic" asp-action="Index" class="nav-link @(actionController == "Clinic|Index" ? "active" : "" )">
                    <i class="nav-icon fas fa-clinic-medical"></i>
                    <p>
                        Clinicas
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Doctor" asp-action="Index" class="nav-link @(actionController == "Doctor|Index" ? "active" : "" )">
                    <i class="nav-icon fas fa-user-md"></i>
                    <p>
                        Doctores
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Patient" asp-action="Index" class="nav-link @(actionController == "Patient|Index" ? "active" : "" )">
                    <i class="nav-icon fas fa-user-injured"></i>
                    <p>
                        Pacientes
                    </p>
                </a>
            </li>
        </ul>
    </li>
</ul>

MedicalApp.WebApp/Views/Shared/_DoctorHome.cshtml
@model MedicalApp.WebApp.Models.HomeViewModel
<div class="text-center">
    <h1 class="display-4">Agenda del día</h1>
</div>
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>@Model.ScheduledAppointmentsCount</h3>

                <p>Programadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-calendar"></i>
                </div>*@
            @*<a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-primary">
            <div class="inner">
                <h3>@Model.ConfirmedAppointmentsCount</h3>

                <p>Confirmadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-user-injured"></i>
                </div>*@
            @*<a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@Model.FinishedAppointmentsCount</h3>

                <p>Finalizadas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-user-md"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-secondary">
            <div class="inner">
                <h3>@Model.CancelledAppointmentsCount</h3>

                <p>Canceladas</p>
            </div>
            @*<div class="icon">
                    <i class="fa fa-clinic-medical"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>*@
        </div>
    </div>
    <!-- ./col -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            @*<div class="card-header">
                    <h3 class="card-title">Citas del día</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>*@
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table m-0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Clínica</th>
                                <th>Paciente</th>
                                <th>Horario</th>
                                <th>Estado</th>
                                <th>Razón</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Appointments)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Clinic.Name</td>
                                    <td>@string.Format("{0} {1}", item.Patient.Name, item.Patient.LastName)</td>
                                    <td>@item.DateTimeStart</td>
                                    <td>
                                        @if (item.Status == AppointmentStatus.Programada)
                                        {
                                            <span class="badge badge-warning">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Confirmada)
                                        {
                                            <span class="badge badge-primary">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Finalizada)
                                        {
                                            <span class="badge badge-success">@item.Status</span>
                                        }
                                        else if (item.Status == AppointmentStatus.Cancelada)
                                        {
                                            <span class="badge badge-secondary">@item.Status</span>
                                        }
                                    </td>
                                    <td>@item.Reason</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

MedicalApp.WebApp/Views/Shared/_DoctorNav.cshtml
@{
    var actionController = ViewContext.RouteData.Values["Controller"].ToString() + "|" + ViewContext.RouteData.Values["Action"].ToString();
}
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Index" class="nav-link @(actionController == "Home|Index" ? "active" : "")">
            <i class="nav-icon fas fa-home"></i>
            <p>
                Inicio
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Dashboard" asp-action="Index" class="nav-link @(actionController == "Dashboard|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
                Dashboard
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Appointment" asp-action="Index" class="nav-link @(actionController == "Appointment|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-calendar"></i>
            <p>
                Citas
            </p>
        </a>
    </li>
    <li class="nav-item @(actionController == "Search|Index" ? "menu-open" : "" )">
        <a href="#" class="nav-link @(actionController == "Search|Index" ? "active" : "" )">
            <i class="nav-icon fas fa-search"></i>
            <p>
                Consultas
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-controller="Search" asp-action="Index" class="nav-link @(actionController == "Search|Index" ? "active" : "" )">
                    <i class="far fa-calendar nav-icon"></i>
                    <p>Citas</p>
                </a>
            </li>
        </ul>
    </li>
</ul>